[package]
name = "avm1-types-bin"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Types for the Flash ActionScript Virtual Machine (AVM1)"
documentation = "https://github.com/open-flash/avm1-types"
homepage = "https://github.com/open-flash/avm1-types"
repository = "https://github.com/open-flash/avm1-types"
readme = "../README.md"
keywords = ["parser", "swf", "avm1"]
license = "AGPL-3.0-or-later"
edition = "2018"

[[bin]]
name = "avm1-types"
path = "src/main.rs"

[dependencies]
serde_json_v8 = "^0.0.1"
avm1-types = { path = "../" }
